version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIR=/app/chroma_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    ports:
      - "8503:8503"
    volumes:
      - ./:/app
    environment:
      - API_URL=http://app:8000
    depends_on:
      - app
    restart: always