FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install streamlit
RUN pip install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 8503

CMD ["streamlit", "run", "ui/app.py", "--server.port=8503", "--server.address=0.0.0.0"]